# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - TourDe

on:
  push:
    branches:
      - main
    paths:
      - 'tourde.ui'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test UI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up Node.js version
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./tourde.ui
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3.1.2
        with:
          name: node-app
          path: 'build'

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2.1.1
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2.2.10
        id: deploy-to-webapp
        with:
          app-name: 'TourDe'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6B9D3FF4FE6440ED94138609F248AA9A }}
          package: 'build'
